model = "gpt-5.2-codex"
model_reasoning_effort = "high"
[projects."/Users/aeluinchen-mac/Work/linebot-gpt-bookkeeper"]
trust_level = "trusted"

[mcp_servers.Notion]
url = "https://mcp.notion.com/mcp"
